const CANVAS_WIDTH = 1024;
const CANVAS_HEIGHT = 600;

const GAME_SPEED = 3;
const GAME_MAXSPEED = 10;

const GAME_GROUND_MARGIN = 80;
const GAME_CEILING_MARGIN = 80;
const GAME_PLAYER_OBSTACLE_VERTICAL_GAP_MARGIN = 50;

const GAME_OBSTACLES_TIME_INTERVAL = 1000; // in ms
const GAME_OBSTACLES_MIN_TIME_INTERVAL = 1; // in s
const GAME_OBSTACLES_MAX_TIME_INTERVAL = 3; // in s

const GAME_COIN_TIME_INTERVAL = 5000; // in ms
const GAME_COIN_MIN_TIME_INTERVAL = 3; // in s
const GAME_COIN_MAX_TIME_INTERVAL = 7; // in s

const GAME_POWERUP_TIME_INTERVAL = 7000; // in ms
const GAME_POWERUP_MIN_TIME_INTERVAL = 5; // in s
const GAME_POWERUP_MAX_TIME_INTERVAL = 8; // in s

const GAME_API_GET_ENDPOINT = "/api/getdata/";
const GAME_API_POST_ENDPOINT = "/api/postdata/";

const ITEM_FPS = 15;
const ITEM_COIN_MATRIX_MIN_ROW = 0;
const ITEM_COIN_MATRIX_MAX_ROW = 5;
const ITEM_COIN_MATRIX_MIN_COLUMN = 0;
const ITEM_COIN_MATRIX_MAX_COLUMN = 10;

const PLAYER_FPS = 15;

const PLAYER_GRAVITY = 0.5;

const PLAYER_JETPACK_THRUST = 1.75;

const OBSTACLE_1_WIDTH = 60;
const OBSTACLE_1_HEIGHT = 130;

const OBSTACLE_2_WIDTH = 130;
const OBSTACLE_2_HEIGHT = 60;

const OBSTACLE_3_WIDTH = 40;
const OBSTACLE_3_HEIGHT = 130;

const OBSTACLE_4_WIDTH = 185;
const OBSTACLE_4_HEIGHT = 55;

const OBSTACLE_ROCKET_WIDTH = 100;
const OBSTACLE_ROCKET_HEIGHT = 50;
const OBSTACLE_ROCKET_SPEEDX = 15;
